language: node_js
node_js:
- 10.16.3
after_success:
- npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: VQZ1fwl4apZoFfWd99BDsCAuIYKuFjrMkEZCz70NKBFX7RdcXFTgse73mwsFnXJE782T5RkXb77kribZsBc+sz+C3rAbnXPWeKD25DasmwfYiNqU5l16gn6QNYsehAvHpo0PSXwsOiAE4L8KDePkgy0wXQ43QkGhcsavV6PeUEvQpxuOT4DNdkCxHIUkihxeNrcZn0Cd9IZD1BqpVksWVyf+ByHbpzIeNT4w5UWk8u1whg9HO2JzyYCJ8HE8BvtbRUqM2R954X401yjqBIK5a4hHUfjht5rTh+c6trZuwgqWmOlW9Ef7i4Q2MpBy+uyf/IilFbAAUTrhOI2mePfu5qp22r5lemRH48x+KN13djjE2fpD8Aa5BX2EfRp7Umogk+RqfUf50lg8Xh44RPs6ssGs4xf800uy8LU6Q7g2h53EDhgPukV8dPV1jE0UB1aXuoJLvsu/67vRJtvC8zKf3e6DXbd8difmxw6Bqo3jCsqhc/gf5xREpJ7a6ZfMWlwoUd33cZYidhQOvkkRSbTurSqrM8Pc3d8NS89IyHf6Ncsx4Sn7Nqt6ir+2Z75TjrzpfDsmfyNtXejfW2JseP39Vpma6yi/4VoNT8SK+kyjY89LoocCjf0MUYGzYfvRq4Qd8Jq3T13hxgHHgGSY5v4TalkUOA4Ev0GRDGSgCxmvY6I=
  app: dmg-teamwork
