language: node_js
node_js:
- 10.16.3
after_success:
- npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: NZ0/yjfN6aKwVg3tkABB2afjOB14f45IHI/BWbi7Qq0ArpKgJoy1X0OjxAYTkwEz3qZIPfkVZyQjJECumVUIc4tbWC+eYQcSrtPxHLLH29jaeyK3K45XEA3pt6ffRwSQkb8W6CiW4MA2XxH8oi8K/nip4M7yu7NcnITvTc/JIx+aNdu3UdYRAUuiFb3hHIlRulZ1EEfjc7EGaHX0/lszzzwHn+BgWWEtPryBQW0T8vy832EL1keaEJhW/klDhheGkQ+yc8MS/SXLOrzKD0hHae5EbbOK1rZ7HQ6XYimmYc1RLXlcXV/FsVbX5JxnmFd+iG6u8lwyAerZPMHyTB3zA4ctA44/gfhX5oc6WGNcrTq4uyX+sYU/22+vg71be1WyfeZBBjHHXCGllUWVLFONxe8cJL6OkxrBKPCZW/8EBNHOfNaPVV98gF6aDp0yu9Bj1ZTXKV5Mv5mJKwisKHiNf2a/rHCxNSI3asTTPv0KmcdItfTqJiNmctXaMPQRrF1VlP57BpTt1Q68p7ejdW3kwclX1Wv4rj02oXh2lfObj9mT2f7D4XlnbcQLiq5mz9JrHLcc6eQR6v6L62mdnexpb1Jwe8C5mIZDjWkAXjekOfUS5oHoE23IOreCyG0AbCNqJfPCcbkFd29Qlswbx//ZoyxyQzYOn9vicbcldSdLNjo=
